variable "DB_NAME" {}
variable "RDS_ENGINE" {}
variable "RDS_ENGINE_VERSION" {}
variable "RDS_INSTANCE_CLASS" {}
//variable "PARAMETER_GROUP_NAME" {}
variable "VPC_ID" {}
variable "PRIVATE_SUBNET_ID" {}
variable "RDS_PORT" {}
variable "PROJECT" {}
variable "ENV" {}
variable "RDS_PG_FAMILY" {}
variable "PRIVATE_SUBNET_CIDR" {}