variable "DB_NAME" {}
variable "ENGINE" {}
variable "ENGINE_VERSION" {}
variable "INSTANCE_CLASS" {}
variable "USER_NAME" {}
variable "PASSWORD" {}
variable "PARAMETER_GROUP_NAME" {}
variable "VPC_ID" {}
variable "PRIVATE_SUBNET_ID" {}